In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats
from scipy.stats import norm, skew #加载一些统计的库
import time
import gc
import math

In [2]:
print('train')
train = pd.read_table('train.txt',sep=' ',index_col=False)

train

In [3]:
test_a = pd.read_table('test.txt',sep=' ',index_col=False)

In [4]:
train[['is_trade','item_id']].groupby('item_id').sum()

                     is_trade
item_id
42172734419742             10
119705681289325             0
139232509090699             0
186228696000288             0
208192717221960             0
271501162750665             4
334417922587028             0
345352588519597             3
412546248320450             0
584480686684468             0
797382621888539             0
1026777098080416            0
1189938696856115            0
1311995018203737            0
1410182414862995            1
1444427800284312            0
1602469463336249            0
1629778605881953            1
1799405320909774            0
1959922772643180            0
2135374266088353           36
2161134221692568            0
2303426035633108            0
2386647587025706            0
2530623823134608            1
2601286427679606            0
2755006412742406            0
2774499220320641            0
2911433477691881            0
3085733239659473            0
...                       ...
9220853176987749679         1
9220865680359951656         0
9221024195352894257         2
9221101527798031408         0
9221236782688562158         0
9221373654223091534         0
9221461901406317802         0
9221505945751022983         1
9221688760621027988         0
9221719428201311015         0
9222006927261582937         0
9222016272947186534         0
9222064293484093314         0
9222098362902134479         2
9222131282588574016         0
9222138256424091701         0
9222169867865830787         0
9222383341771442824         0
9222384706282365215         0
9222405470801777723         2
9222416214563495084         0
9222427613233602626         0
9222644101727866521         2
9222778018896286639         0
9222822722462880089        32
9222850410250537082         0
9222876295690279005        23
9222897970029908113         1
9222990352563577630         0
9223091646754113652         0

[84677 rows x 1 columns]

In [5]:
temp = pd.DataFrame()

In [7]:
temp['i_pv'] = (train[['item_id','is_trade']].groupby('item_id').sum()).reset_index()[['is_trade']]

In [8]:
temp['item_id'] = (train[['item_id','is_trade']].groupby('item_id').sum()).reset_index()[['item_id']]

In [9]:
temp

       s_pv  i_pv              item_id
0        10    10       42172734419742
1         0     0      119705681289325
2         0     0      139232509090699
3         0     0      186228696000288
4         0     0      208192717221960
5         4     4      271501162750665
6         0     0      334417922587028
7         3     3      345352588519597
8         0     0      412546248320450
9         0     0      584480686684468
10        0     0      797382621888539
11        0     0     1026777098080416
12        0     0     1189938696856115
13        0     0     1311995018203737
14        1     1     1410182414862995
15        0     0     1444427800284312
16        0     0     1602469463336249
17        1     1     1629778605881953
18        0     0     1799405320909774
19        0     0     1959922772643180
20       36    36     2135374266088353
21        0     0     2161134221692568
22        0     0     2303426035633108
23        0     0     2386647587025706
24        1     1     2530623823134608
25        0     0     2601286427679606
26        0     0     2755006412742406
27        0     0     2774499220320641
28        0     0     2911433477691881
29        0     0     3085733239659473
...     ...   ...                  ...
84647     1     1  9220853176987749679
84648     0     0  9220865680359951656
84649     2     2  9221024195352894257
84650     0     0  9221101527798031408
84651     0     0  9221236782688562158
84652     0     0  9221373654223091534
84653     0     0  9221461901406317802
84654     1     1  9221505945751022983
84655     0     0  9221688760621027988
84656     0     0  9221719428201311015
84657     0     0  9222006927261582937
84658     0     0  9222016272947186534
84659     0     0  9222064293484093314
84660     2     2  9222098362902134479
84661     0     0  9222131282588574016
84662     0     0  9222138256424091701
84663     0     0  9222169867865830787
84664     0     0  9222383341771442824
84665     0     0  9222384706282365215
84666     2     2  9222405470801777723
84667     0     0  9222416214563495084
84668     0     0  9222427613233602626
84669     2     2  9222644101727866521
84670     0     0  9222778018896286639
84671    32    32  9222822722462880089
84672     0     0  9222850410250537082
84673    23    23  9222876295690279005
84674     1     1  9222897970029908113
84675     0     0  9222990352563577630
84676     0     0  9223091646754113652

[84677 rows x 3 columns]

In [10]:
train = pd.merge(train[['instance_id','item_id']],temp[['item_id','i_pv']],on=['item_id'],how='left')
test_a = pd.merge(test_a[['instance_id','item_id']],temp[['item_id','i_pv']],on=['item_id'],how='left')

In [11]:
train.count()

instance_id    10432036
item_id        10432036
i_pv           10432036
dtype: int64

In [12]:
test_a.count()

instance_id    519888
item_id        519888
i_pv           517011
dtype: int64

In [13]:
test_a = test_a.fillna(0)

In [14]:
test_a.count()

instance_id    519888
item_id        519888
i_pv           519888
dtype: int64

In [15]:
train[['instance_id','i_pv']].to_csv('train_ipv.csv',index=False) 
test_a[['instance_id','i_pv']].to_csv('test_ipv.csv',index=False)