In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats
from scipy.stats import norm, skew #加载一些统计的库
import time
import gc
import math

In [2]:
print('train')
train = pd.read_table('train.txt',sep=' ',index_col=False)

train

In [3]:
test_a = pd.read_table('test.txt',sep=' ',index_col=False)

In [4]:
train[['is_trade','shop_id']].groupby('shop_id').sum()

                     is_trade
shop_id
369399843124909             5
1149611804947766            0
1394879586952028            0
1521332146149762            0
2152308100603334            1
2773765767290054            4
3264820913535821            1
4131379046539124            2
4267495697515624            1
4299863091308684            0
4345966903769309            0
4819657811349762            8
4973355590187660            1
5608882511569565            0
5693260178969180            0
5958394049607973            0
6338940839651047            0
6829438120144100           20
7576748580353559            0
8168785132985395            0
8232448400649954           74
8500745961405662           13
9129419305384654            2
9312337510151336            4
9520371888514908            0
9884570751253386            0
9979234807583790            0
10109274603363453          11
10347353543048130           0
10702616585969969           0
...                       ...
9211630890479557190         0
9211678904580998296         0
9211834447046719442         0
9212196466489524147         0
9212371706042864205         0
9212389407695829121         2
9212691534724038751         0
9212713621321316221        27
9212915450971441913         1
9213272433055271069         0
9213295951782058567         0
9214210404567355325         0
9214294661117824617         1
9215339032529533876         0
9215998929638367660         0
9216177718599719906         0
9216754376548783007         0
9217685770845534520         1
9217922069272028572         0
9218316035013870429         1
9218339035659539455         0
9218424035422124518         0
9219090318163251527         0
9219189489699864552         1
9219799509241098169         0
9220136402676883386         0
9220810267050812290         8
9221828983418040970         6
9221840441828021133         1
9222198553207956009         0

[24942 rows x 1 columns]

In [5]:
temp = pd.DataFrame()

In [6]:
temp['s_pv'] = (train[['shop_id','is_trade']].groupby('shop_id').sum()).reset_index()[['is_trade']]

In [7]:
temp['shop_id'] = (train[['shop_id','is_trade']].groupby('shop_id').sum()).reset_index()[['shop_id']]

In [8]:
temp

       s_pv              shop_id
0         5      369399843124909
1         0     1149611804947766
2         0     1394879586952028
3         0     1521332146149762
4         1     2152308100603334
5         4     2773765767290054
6         1     3264820913535821
7         2     4131379046539124
8         1     4267495697515624
9         0     4299863091308684
10        0     4345966903769309
11        8     4819657811349762
12        1     4973355590187660
13        0     5608882511569565
14        0     5693260178969180
15        0     5958394049607973
16        0     6338940839651047
17       20     6829438120144100
18        0     7576748580353559
19        0     8168785132985395
20       74     8232448400649954
21       13     8500745961405662
22        2     9129419305384654
23        4     9312337510151336
24        0     9520371888514908
25        0     9884570751253386
26        0     9979234807583790
27       11    10109274603363453
28        0    10347353543048130
29        0    10702616585969969
...     ...                  ...
24912     0  9211630890479557190
24913     0  9211678904580998296
24914     0  9211834447046719442
24915     0  9212196466489524147
24916     0  9212371706042864205
24917     2  9212389407695829121
24918     0  9212691534724038751
24919    27  9212713621321316221
24920     1  9212915450971441913
24921     0  9213272433055271069
24922     0  9213295951782058567
24923     0  9214210404567355325
24924     1  9214294661117824617
24925     0  9215339032529533876
24926     0  9215998929638367660
24927     0  9216177718599719906
24928     0  9216754376548783007
24929     1  9217685770845534520
24930     0  9217922069272028572
24931     1  9218316035013870429
24932     0  9218339035659539455
24933     0  9218424035422124518
24934     0  9219090318163251527
24935     1  9219189489699864552
24936     0  9219799509241098169
24937     0  9220136402676883386
24938     8  9220810267050812290
24939     6  9221828983418040970
24940     1  9221840441828021133
24941     0  9222198553207956009

[24942 rows x 2 columns]

In [9]:
train = pd.merge(train[['instance_id','shop_id']],temp[['shop_id','s_pv']],on=['shop_id'],how='left')
test_a = pd.merge(test_a[['instance_id','shop_id']],temp[['shop_id','s_pv']],on=['shop_id'],how='left')

In [10]:
train.count()

instance_id    10432036
shop_id        10432036
s_pv           10432036
dtype: int64

In [11]:
test_a.count()

instance_id    519888
shop_id        519888
s_pv           519145
dtype: int64

In [12]:
test_a = test_a.fillna(0)

In [13]:
test_a.count()

instance_id    519888
shop_id        519888
s_pv           519888
dtype: int64

In [14]:
train[['instance_id','s_pv']].to_csv('train_pv.csv',index=False) 
test_a[['instance_id','s_pv']].to_csv('test_pv.csv',index=False)

In [15]:
test_a = pd.read_table('test1.txt',sep=' ',index_col=False)

In [16]:
test_a = pd.merge(test_a[['instance_id','shop_id']],temp[['shop_id','s_pv']],on=['shop_id'],how='left')

In [17]:
test_a.count()

instance_id    1209768
shop_id        1209768
s_pv           1208025
dtype: int64

In [18]:
test_a = test_a.fillna(0)

In [19]:
test_a.count()

instance_id    1209768
shop_id        1209768
s_pv           1209768
dtype: int64

In [20]:
test_a[['instance_id','s_pv']].to_csv('test1_pv.csv',index=False)